# Generated by Django 2.1.5 on 2019-02-18 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tamanho', models.IntegerField(help_text='Ingresar solo números en mililitros (ml)')),
                ('sabor', models.CharField(max_length=30)),
                ('proveedor', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('GASE', 'Gaseosa'), ('CERV', 'Cerveza'), ('WHIS', 'Whisky'), ('VOD', 'Vodka')], default='GASE', max_length=3)),
                ('contenido_alcohol', models.IntegerField(default=0)),
                ('precio', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('no_pedido', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('f_pedido', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.IntegerField(default=0)),
                ('condicion_pago', models.CharField(choices=[('CONT', 'Contado'), ('CRED', 'Crédito')], default='CONT', max_length=4)),
                ('medio_pago', models.CharField(choices=[('EFEC', 'Efectivo'), ('TARJ', 'Tarjeta')], default='EFEC', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_detalle', to='catalogo.Bebida')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_detalle', to='catalogo.Pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='bebidas',
            field=models.ManyToManyField(through='catalogo.PedidoDetalle', to='catalogo.Bebida'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cliente'),
        ),
    ]
