# Generated by Django 2.1.5 on 2019-02-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='tipo',
            field=models.CharField(choices=[('GASE', 'Gaseosa'), ('CERV', 'Cerveza'), ('WHIS', 'Whisky'), ('VOD', 'Vodka')], default='GASE', max_length=4),
        ),
    ]
